apiVersion: v1
kind: ServiceAccount
metadata:
  name: pharos-batch
  namespace: core-services
automountServiceAccountToken: true # used by client-go for InClusterConfig()
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: core-services
  name: pharos-batch
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "deletecollection"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-batch
  namespace: core-services
subjects:
- kind: ServiceAccount
  name: pharos-batch
  namespace: core-services
roleRef:
  kind: Role 
  name: pharos-batch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: core-services
  name: pharos-batch
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["persistentvolumes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pharos-batch
  namespace: core-services
subjects:
- kind: ServiceAccount
  name: pharos-batch
  namespace: core-services
roleRef:
  kind: ClusterRole 
  name: pharos-batch
  apiGroup: rbac.authorization.k8s.io
