apiVersion: batch/v1
kind: Job
metadata:
  name: pharos-scan-filesystems-testrunid
  namespace: core-services
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccount: pharos-batch
      containers:
      - name: pharos-scan-filesystems-testrunid
        image: pharos-batch:0.0.1
        imagePullPolicy: Never
        env:
        - name: RUN_MODE
          value: SCAN_FILESYSTEMS
        - name: SERVICE_ID
          value: pharos-batch
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: PARENT_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: PARENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: IMAGE_NAME
          value: pharos-batch:0.0.1
        - name: FILE_CHUNK_SIZE
          value: "1G"
        - name: FILESYSTEM_ROOT_DIRECTORY
          value: /mnt/pvcs/
        - name: QUARANTINE_PVC_NAME
          value: quarantine-pvc
        - name: VIRUS_DEFINITION_PVC_NAME
          value: virus-defs
        volumeMounts:
        - mountPath: /mnt/pvcs/efs-root
          name: filesystem
        - mountPath: /mnt/quarantine
          name: quarantine
      volumes:
        - name: filesystem
          persistentVolumeClaim:
            claimName: efs-root
        - name: quarantine
          persistentVolumeClaim:
            claimName: quarantine-pvc
            
