apiVersion: batch/v1
kind: Job
metadata:
  name: pharos-log-filesystems-testrunid
  namespace: core-services
  labels:
    service: pharos-batch
    runMode: LOG_FILESYSTEMS
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      serviceAccount: pharos-batch
      containers:
      - name: pharos-log-filesystems-testrunid
        image: pharos-batch:0.0.1
        imagePullPolicy: Never
        env:
        - name: RUN_MODE
          value: LOG_FILESYSTEMS
        - name: SERVICE_ID
          value: pharos-batch
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_ACCOUNT_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: PARENT_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: PARENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: IMAGE_NAME
          value: pharos-batch:0.0.1
        - name: FILE_CHUNK_SIZE
          value: "500M"
        - name: FILESYSTEM_ROOT_DIRECTORY
          value: /mnt/
        volumeMounts:
        - mountPath: /mnt/efs-root
          name: filesystem
         - mountPath: /mnt/efs-root2
          name: filesystem2
      volumes:
        - name: filesystem
          persistentVolumeClaim:
            claimName: efs-root
        - name: filesystem2
          persistentVolumeClaim:
            claimName: efs-root2

    
