apiVersion: v1
kind: ServiceAccount
metadata:
  name: pharos-batch
  namespace: default
automountServiceAccountToken: true # used by client-go for InClusterConfig()
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pharos-batch
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create", "update", "delete", "deletecollection"]
# not sure if this is needed as pods are deleted as part of Jobs 
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list","delete", "deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pharos-batch
  namespace: default
subjects:
- kind: ServiceAccount
  name: pharos-batch
  namespace: default
roleRef:
  kind: Role 
  name: pharos-batch
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: pharos-batch
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["persistentvolumes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pharos-batch
  namespace: default
subjects:
- kind: ServiceAccount
  name: pharos-batch
  namespace: default
roleRef:
  kind: ClusterRole 
  name: pharos-batch
  apiGroup: rbac.authorization.k8s.io