apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: "2022-11-19T17:25:50Z"
  labels:
    runId: run-2022-11-19-17-25-38
    runMode: SCAN_CHUNK
    service: pharos-batch
  name: pharos-scan-chunk-5-run-2022-11-19-17-25-38-efs-root
  namespace: core-services
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      job-name: pharos-scan-chunk-5-run-2022-11-19-17-25-38-efs-root
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 2da00ec8-56bc-4805-bef2-c8ea52446921
        job-name: pharos-scan-chunk-5-run-2022-11-19-17-25-38-efs-root
    spec:
      containers:
      - env:
        - name: RUN_MODE
          value: SCAN_CHUNK
        - name: RUN_ID
          value: run-2022-11-19-17-25-38
        - name: SERVICE_ID
          value: pharos-batch
        - name: NAMESPACE
          value: core-services
        - name: SERVICE_ACCOUNT
          value: pharos-batch
        - name: PARENT_UID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.uid
        - name: PARENT_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: CHUNK_NUMBER
          value: "5"
        - name: FILESYSTEM_PVC_NAME
          value: efs-root
        image: pharos-batch:0.0.1
        imagePullPolicy: IfNotPresent
        name: pharos-batch
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mnt/pvcs/efs-root
          name: filesystem
        - mountPath: /mnt/quarantine
          name: quarantine
        - mountPath: /var/lib/clamav
          name: virus-definitions
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: pharos-batch
      serviceAccountName: pharos-batch
      terminationGracePeriodSeconds: 30
      volumes:
      - name: filesystem
        persistentVolumeClaim:
          claimName: efs-root
      - name: quarantine
        persistentVolumeClaim:
          claimName: quarantine-pvc
      - name: virus-definitions
        persistentVolumeClaim:
          claimName: virus-defs
